/*
Code de suppression de tous les objets du schéma
*/

-- Suppression des tables
DROP TABLE G_GEOTECH.TA_GEOTECH_FAMILLE_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_FAMILLE CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_LIBELLE CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_ETUDE CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_SITE CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_ETUDE_LOG CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_SITE_LOG CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_BUREAU_ETUDE CASCADE CONSTRAINTS;
/*DROP TABLE G_GEOTECH.TA_GEOTECH_REPERTOIRE CASCADE CONSTRAINTS;
DROP TABLE G_GEOTECH.TA_GEOTECH_FICHIER CASCADE CONSTRAINTS;
*/

-- Suppression des vues
DROP VIEW G_GEOTECH.V_GEOTECH_VISUALISATION_SITE_ETUDE;
--DROP VIEW G_GEOTECH.V_CHEMIN_FICHIER_GEOTECH;

-- Suppression des métadonnées spatiales
DELETE FROM USER_SDO_GEOM_METADATA 
WHERE TABLE_NAME = 'TA_GEOTECH_SITE';
COMMIT;

DELETE FROM USER_SDO_GEOM_METADATA 
WHERE TABLE_NAME = 'TA_GEOTECH_SITE_LOG';
COMMIT;

DELETE FROM USER_SDO_GEOM_METADATA 
WHERE TABLE_NAME = 'V_GEOTECH_VISUALISATION_SITE_ETUDE';
COMMIT;

-- Suppression des séquences
DROP SEQUENCE G_GEOTECH.SEQ_TA_GEOTECH_FAMILLE_OBJECTID;
DROP SEQUENCE G_GEOTECH.SEQ_TA_GEOTECH_LIBELLE_OBJECTID;
DROP SEQUENCE G_GEOTECH.SEQ_TA_GEOTECH_ETUDE_OBJECTID;
DROP SEQUENCE G_GEOTECH.SEQ_TA_GEOTECH_SITE_OBJECTID;
DROP SEQUENCE G_GEOTECH.SEQ_TA_GEOTECH_BUREAU_ETUDE_OBJECTID;

-- Suppression des fonctions
DROP FUNCTION GET_CODE_INSEE_CONTAIN_POINT;

-- Suppression des déclencheurs
/*DROP TRIGGER A_IUD_TA_GEOTECH_ETUDE_LOG;
DROP TRIGGER A_IUD_TA_GEOTECH_SITE_LOG;*/